#!/usr/bin/env node
// ============================================================================
// Builds the org from org/**/*.md into one generated module, written twice:
// once for the app (src/lib/org.generated.ts) and once for the edge functions
// (supabase/functions/_shared/org.generated.ts), so both read the same seats.
// Run: npm run org   (also runs before every build)
// ============================================================================
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const orgDir = join(root, 'org')

function walk(dir) {
  const out = []
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) out.push(...walk(p))
    else if (name.endsWith('.md')) out.push(p)
  }
  return out.sort()
}

function parseValue(raw) {
  const v = raw.trim()
  if (/^\[.*\]$/.test(v)) return v.slice(1, -1).split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean)
  if (/^".*"$/.test(v) || /^'.*'$/.test(v)) return v.slice(1, -1)
  if (/^-?\d+$/.test(v)) return Number(v)
  return v
}

function parse(file) {
  const text = readFileSync(file, 'utf8')
  const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/)
  if (!m) throw new Error(`${relative(root, file)}: missing frontmatter`)
  const meta = {}
  for (const line of m[1].split('\n')) {
    const mm = line.match(/^([a-zA-Z_]+):\s*(.*)$/)
    if (mm) meta[mm[1]] = parseValue(mm[2])
  }
  const sections = {}
  let current = 'body'
  for (const line of m[2].split('\n')) {
    const h = line.match(/^##\s+(.+)$/)
    if (h) { current = h[1].trim().toLowerCase(); sections[current] = ''; continue }
    sections[current] = (sections[current] ?? '') + line + '\n'
  }
  const clean = (s) => (s ?? '').replace(/\n{3,}/g, '\n\n').trim()
  return { meta, sections: Object.fromEntries(Object.entries(sections).map(([k, v]) => [k, clean(v)])) }
}

/** "## Charter" prose is wrapped at 80 columns in the file; join it back into paragraphs. */
const prose = (s) => (s ?? '').split(/\n{2,}/).map((p) => p.replace(/\s*\n\s*/g, ' ').trim()).filter(Boolean).join('\n\n')
/** Bullet sections keep their bullets but unwrap continuation lines. */
const bullets = (s) => (s ?? '').replace(/\n(?![-\s])/g, ' ').replace(/\n\s+(?!-)/g, ' ').trim()
const plays = (s) => (s ?? '').split('\n').map((l) => l.match(/^-\s+\*\*(.+?)\*\*:\s*(.+)$/)).filter(Boolean).map((mm) => ({ label: mm[1].trim(), task: mm[2].trim() }))

const departments = [], roles = [], tools = []
for (const file of walk(orgDir)) {
  const rel = relative(orgDir, file)
  // Only the three folders below are seats. Anything else under org/ (brand
  // guidelines, notes) is the founder's and is left alone.
  if (!/^(departments|roles|tools)\//.test(rel)) continue
  const { meta, sections } = parse(file)
  if (rel.startsWith('departments/')) {
    departments.push({ key: meta.key, name: meta.name, tagline: meta.tagline ?? '', accent: meta.accent ?? '#888888', mark: meta.mark ?? meta.name.slice(0, 2).toUpperCase(), order: meta.order ?? 99, tools: meta.tools ?? [], mandate: prose(sections.mandate), learning: prose(sections['weekly learning']) })
  } else if (rel.startsWith('roles/')) {
    for (const k of ['key', 'dept', 'seat', 'name']) if (!meta[k]) throw new Error(`${rel}: missing ${k}`)
    roles.push({ key: meta.key, dept: meta.dept, seat: meta.seat, brand: meta.brand ?? null, name: meta.name, title: meta.title ?? '', owns: meta.owns ?? '', defers: meta.defers ?? '', learnsFrom: meta.learns_from ?? '', charter: prose(sections.charter), principles: bullets(sections.principles), never: bullets(sections.never), plays: plays(sections.plays), file: rel })
  } else if (rel.startsWith('tools/')) {
    tools.push({ key: meta.key, name: meta.name, status: meta.status ?? 'planned', cost: meta.cost ?? '', url: meta.url ?? '', blurb: prose(sections.body) })
  }
}
departments.sort((a, b) => a.order - b.order)

// Sanity: every role's department exists; one lead per (dept, brand).
const deptKeys = new Set(departments.map((d) => d.key))
for (const r of roles) if (!deptKeys.has(r.dept)) throw new Error(`${r.file}: unknown dept ${r.dept}`)
const leads = new Map()
for (const r of roles.filter((x) => x.seat === 'lead')) {
  const k = `${r.dept}/${r.brand ?? '*'}`
  if (leads.has(k)) throw new Error(`two leads for ${k}: ${leads.get(k)} and ${r.file}`)
  leads.set(k, r.file)
}

const header = `// GENERATED by scripts/build-org.mjs from org/**/*.md. Do not edit: edit the markdown and run \`npm run org\`.
export type OrgSeat = 'lead' | 'member'
export interface OrgDept { key: string; name: string; tagline: string; accent: string; mark: string; order: number; tools: string[]; mandate: string; learning: string }
export interface OrgRole { key: string; dept: string; seat: OrgSeat; brand: string | null; name: string; title: string; owns: string; defers: string; learnsFrom: string; charter: string; principles: string; never: string; plays: { label: string; task: string }[]; file: string }
export interface OrgTool { key: string; name: string; status: string; cost: string; url: string; blurb: string }
export const ORG: { departments: OrgDept[]; roles: OrgRole[]; tools: OrgTool[] } = `
const body = JSON.stringify({ departments, roles, tools }, null, 2)
for (const out of ['src/lib/org.generated.ts', 'supabase/functions/_shared/org.generated.ts']) {
  writeFileSync(join(root, out), header + body + '\n')
}
console.log(`org: ${departments.length} departments, ${roles.length} seats (${roles.filter((r) => r.seat === 'lead').length} leads), ${tools.length} tools`)
